#!/usr/bin/env python3
"""
HTML to C Header Converter with Gzip Compression
Converts HTML files to compressed C headers for ESP-IDF web servers.

Usage:
    python html_to_header.py <input.html> <output.h>
    python html_to_header.py main/www/dashboard.html main/www/dashboard.html.h
"""

import sys
import gzip
import os


def html_to_header(input_file, output_file):
    """
    Convert HTML file to gzipped C header file.
    
    Args:
        input_file: Path to input HTML file
        output_file: Path to output C header file
    """
    
    # Read HTML file
    try:
        with open(input_file, 'rb') as f:
            html_data = f.read()
    except FileNotFoundError:
        print(f"Error: Input file '{input_file}' not found")
        sys.exit(1)
    except Exception as e:
        print(f"Error reading input file: {e}")
        sys.exit(1)
    
    # Compress with gzip
    compressed_data = gzip.compress(html_data, compresslevel=9)
    
    # Calculate sizes
    original_size = len(html_data)
    compressed_size = len(compressed_data)
    compression_ratio = (1 - compressed_size / original_size) * 100
    
    print(f"Original size:    {original_size:,} bytes")
    print(f"Compressed size:  {compressed_size:,} bytes")
    print(f"Compression:      {compression_ratio:.1f}%")
    
    # Generate variable name from filename
    base_name = os.path.splitext(os.path.basename(input_file))[0]
    var_name = base_name.replace('.', '_').replace('-', '_')
    
    # Generate C header file
    header_content = f"""/**
 * @file {os.path.basename(output_file)}
 * @brief Embedded gzip-compressed HTML dashboard
 * 
 * Auto-generated from {os.path.basename(input_file)}
 * Original size: {original_size:,} bytes
 * Compressed size: {compressed_size:,} bytes
 * Compression ratio: {compression_ratio:.1f}%
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Regenerate with: python tools/html_to_header.py {input_file} {output_file}
 */

#ifndef {var_name.upper()}_H
#define {var_name.upper()}_H

#include <stdint.h>

// Gzip-compressed HTML data
const uint8_t {var_name}_gz[] = {{
"""
    
    # Add compressed data as hex array
    for i in range(0, len(compressed_data), 16):
        chunk = compressed_data[i:i+16]
        hex_bytes = ', '.join(f'0x{b:02x}' for b in chunk)
        header_content += f"    {hex_bytes},\n"
    
    # Remove trailing comma
    header_content = header_content.rstrip(',\n') + '\n'
    
    # Add footer
    header_content += f"""
}};

// Size of compressed data
const size_t {var_name}_gz_len = sizeof({var_name}_gz);

#endif // {var_name.upper()}_H
"""
    
    # Write output file
    try:
        # Create output directory if it doesn't exist
        output_dir = os.path.dirname(output_file)
        if output_dir and not os.path.exists(output_dir):
            os.makedirs(output_dir)
        
        with open(output_file, 'w') as f:
            f.write(header_content)
        
        print(f"Generated: {output_file}")
    except Exception as e:
        print(f"Error writing output file: {e}")
        sys.exit(1)


def main():
    """Main entry point."""
    if len(sys.argv) != 3:
        print("Usage: python html_to_header.py <input.html> <output.h>")
        print("Example: python html_to_header.py main/www/dashboard.html main/www/dashboard.html.h")
        sys.exit(1)
    
    input_file = sys.argv[1]
    output_file = sys.argv[2]
    
    print(f"Converting {input_file} to {output_file}...")
    html_to_header(input_file, output_file)
    print("Done!")


if __name__ == '__main__':
    main()
